site_name: Sistemas de Machine Learning Accio



theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Modo escuro
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

nav:
  - Início: index.md
  - Arquitetura:
      - Visão Geral: arquitetura/visao-geral.md
      - Coleta de Dados: arquitetura/01-coleta-dados.md
      - Banco Vetorial: arquitetura/02-banco-vetorial.md
      - Pipeline RAG: arquitetura/03-pipeline-rag.md
      - Infra e Modelos: arquitetura/04-infra-modelos-local.md
      - Métricas e Benchmark: arquitetura/05-metricas-benchmark.md
  - Avaliações:
      - Dataset de Teste: avaliacao/dataset-teste.md
      - Nuvem vs. Local: avaliacao/comparacao-nuvem-local.md
      - Avaliação RAG: avaliacao/avaliacao-rag.md
      - Resultados: avaliacao/resultados-finais.md
  - Guias:
      - Como usar: guias/como-usar.md


plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - tables