site_name: FatoUnB - Documentação Técnica
site_description: Sistema automatizado de fact-checking e combate a boatos na Universidade de Brasília criado para a disciplina de Sistemas de Machine Learning 2026.2.
site_author: Equipe Accio

theme:
  name: material
  language: pt-BR
  palette:
    # Modo Escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
    # Modo Claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Início: 
    - index.md
  - Guiding Questions: 
    - guiding_questions.md
  - Módulos:
      - Coleta de Dados: modulos/01-coleta-dados.md
      - Banco Vetorial: modulos/02-banco-vetorial.md
      - Pipeline RAG & Checagem: modulos/03-pipeline-rag.md
      - Infra e Modelos: modulos/04-infra-modelos-local.md
      - Métricas e Benchmark: modulos/05-metricas-benchmark.md
      - Avaliações:
        - Dataset de Teste: modulos/avaliacao/dataset-teste.md
        - Nuvem vs. Local: modulos/avaliacao/comparacao-nuvem-local.md
        - Avaliação RAG: modulos/avaliacao/avaliacao-rag.md
        - Resultados: modulos/avaliacao/resultados-finais.md
